### ISSUE TITLE
teletype new broken in 0.9.0

### ISSUE THREAD

**Issue by Flipez** [piotrmurach/tty#49]
### Are you in the right place?
* For issues or feature requests file a GitHub issue in this repository
* For general questions or discussion post in [Gitter](https://gitter.im/piotrmurach/tty)

### Describe the problem
teletype new does not work in the lates version (0.9.0)

### Steps to reproduce the problem
```
teletype new app
```

### Actual behaviour
```
	 9: from /usr/local/lib/ruby/gems/2.6.0/bin/teletype:23:in `load'
	 8: from /usr/local/lib/ruby/gems/2.6.0/gems/tty-0.9.0/exe/teletype:14:in `<top (required)>'
	 7: from /usr/local/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	 6: from /usr/local/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	 5: from /usr/local/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	 4: from /usr/local/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	 3: from /usr/local/lib/ruby/gems/2.6.0/gems/tty-0.9.0/lib/tty/cli.rb:128:in `new'
	 2: from /usr/local/lib/ruby/gems/2.6.0/gems/tty-0.9.0/lib/tty/commands/new.rb:146:in `execute'
	 1: from /usr/local/lib/ruby/gems/2.6.0/gems/tty-0.9.0/lib/tty/commands/new.rb:234:in `add_required_libs_to_gemspec'
/usr/local/lib/ruby/gems/2.6.0/gems/tty-0.9.0/lib/tty/plugins.rb:58:in `load_from': undefined method `runtime_dependencies' for nil:NilClass (NoMethodError)
```
What happened? This could be a description, log output, error raised etc...

### Expected behaviour
teletype should scaffold a new app

### Describe your environment

* OS version: macOS 10.14.1
* Ruby version: 2.6
* TTY version: 0.9.0
